name: CI

on:
  - pull_request
  - push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable corepack & install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Build
        run: pnpm run build

      - name: Type Check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test
