name: Publish Packages

on:
  push:
    branches:
      - main # 또는 master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Publish packages with Lerna
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx lerna publish from-package --yes
